### ISSUE TITLE
Not finding the logging plugin loki

### ISSUE THREAD

**Issue by Therealchainman** [ruanbekker/loki-docker-nginx-example#1]
ERROR: for my-nginx-service  Cannot create container for service my-nginx-service: error looking up logging plugin loki: plugin "loki" not found

ERROR: for logger  Cannot create container for service logger-app: error looking up logging plugin loki: plugin "loki" not found

ERROR: for my-nginx-service  Cannot create container for service my-nginx-service: error looking up logging plugin loki: plugin "loki" not found

ERROR: for logger-app  Cannot create container for service logger-app: error looking up logging plugin loki: plugin "loki" not found
ERROR: Encountered errors while bringing up the project.

I'm trying to work out what could be causing this issue.  Let me know if you want more information.

**Comment by neredera** [comment]
You need the [Loki Docker Driver](https://grafana.com/docs/loki/latest/clients/docker-driver/)
